### ISSUE TITLE
Trouble starting container

### ISSUE THREAD

**Issue by maddox** [macropin/docker-strider#8]
I'm not sure what exactly is going on. But `strider` can't be run. Any time it is, this is the error that I see. The container won't come up because of this.

I'm not sure why it can't find `backoff`. I built the image from scratch from this repo and it still does it. So it doesn't appear to be a bad build.

Any ideas what might be causing this?

```>> Strider Docker Image master Starting...
entry.sh >> Running addUser
module.js:487
    throw err;
    ^

Error: Cannot find module 'backoff'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/node_modules/ldapjs/lib/client/client.js:9:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/node_modules/ldapjs/lib/client/index.js:7:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/node_modules/ldapjs/lib/index.js:5:14)
    at Module._compile (module.js:569:30)
```

**Comment by phamid** [comment]
This bug because new node container cleans cache forsibly. [https://github.com/nodejs/docker-node/blob/master/Dockerfile-onbuild.template](url)

**Comment by itfarrier** [comment]
This bug because new node container cleans cache forsibly. [https://github.com/nodejs/docker-node/blob/master/Dockerfile-onbuild.template](https://github.com/nodejs/docker-node/blob/master/Dockerfile-onbuild.template)

**Comment by macropin** [comment]
Can you run an image pulled from the hub eg `docker.io/macropin/strider:latest`?
